[package]
name = "letter"
version = "0.4.0"
entrypoint = "lib.typ"
authors = ["Benedikt Claus"]
license = "MIT"
description = "Personal letter package"

[template]
path = "template"
entrypoint = "main.typ"